// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmepfdpgilibpiyoyywb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZXBmZHBnaWxpYnBpeW95eXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDIyMTUsImV4cCI6MjA2OTE3ODIxNX0.cl_pOCITaTj87G8QrBNDy-pOLOzG4ylv_GZ-293ni3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});